sonar.projectKey=task-management-system-jp2026
sonar.projectName=Task Management System JP2026
sonar.sources=app,public,views
sonar.exclusions=vendor/**,tests/**
sonar.php.coverage.reportPaths=coverage.xml
sonar.host.url=http://host.docker.internal:9000